- name: Install and configure Docker on AWS EC2
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Set compose arch
      ansible.builtin.set_fact:
        compose_arch: "{{ 'aarch64' if ansible_facts.architecture == 'aarch64' else 'x86_64' }}"

    - name: Create docker cli-plugins directory
      ansible.builtin.file:
        path: "/usr/local/lib/docker/cli-plugins"
        state: directory
        mode: "0755"

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v2.38.2/docker-compose-linux-{{ compose_arch }}"
        dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
        mode: "0755"

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add remote user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
  handlers:
    - name: restart docker
      ansible.builtin.service:
        name: docker
        state: restarted

- name: Install and configure CloudWatch monitoring on AWS EC2
  hosts: all
  become: true
  tasks:
    - name: Install CloudWatch
      ansible.builtin.yum:
        name: amazon-cloudwatch-agent
        state: present

    - name: Create CloudWatch agent configuration
      ansible.builtin.copy:
        content: |
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "cwagent"
            },
            "metrics": {
              "namespace": "CWAgent/{{ app_name }}",
              "metrics_collected": {
                "cpu": {
                  "measurement": [
                    "cpu_usage_idle",
                    "cpu_usage_iowait",
                    "cpu_usage_user",
                    "cpu_usage_system"
                  ],
                  "metrics_collection_interval": 60,
                  "totalcpu": false
                },
                "disk": {
                  "measurement": [
                    "used_percent"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "*"
                  ]
                },
                "diskio": {
                  "measurement": [
                    "io_time"
                  ],
                  "metrics_collection_interval": 60,
                  "resources": [
                    "*"
                  ]
                },
                "mem": {
                  "measurement": [
                    "mem_used_percent"
                  ],
                  "metrics_collection_interval": 60
                },
                "netstat": {
                  "measurement": [
                    "tcp_established",
                    "tcp_time_wait"
                  ],
                  "metrics_collection_interval": 60
                },
                "swap": {
                  "measurement": [
                    "swap_used_percent"
                  ],
                  "metrics_collection_interval": 60
                }
              }
            }
          }
        dest: "/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json"
        mode: "0644"
        backup: yes

    # Start CloudWatch Agent
    - name: Start CloudWatch agent with configuration
      ansible.builtin.command:
        cmd: >
          amazon-cloudwatch-agent-ctl
          -a fetch-config -m ec2 -s 
          -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s
      register: cw_start_result
