services:
  traefik:
    image: "traefik:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./acme.json:/etc/traefik/acme.json"
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "{{ app_name }}-{{environment_name}}"
        awslogs-stream: "traefik"
        awslogs-create-group: "true"
        awslogs-create-stream: "true"
networks:
  default:
    name: {{ app_name }}
