- name: Empty GCS Bucket
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Delete all files from GCS bucket
      debug:
        msg: "Deleting files from GCP bucket is currently not supported."
