- name: Build and Deploy Frontend to GCS
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Run build command
      ansible.builtin.command: "{{ build_cmd }}"
      args:
        chdir: "{{ project_root }}"
      environment: "{{ {'PATH': (project_root ~ '/' ~ build_path ~ ':' if build_path else '') ~ lookup('env', 'PATH'), 'HOME': lookup('env', 'HOME')} | combine(build_env_vars | default({})) }}"

    - name: Sync build directory to GCS
      google.cloud.gcp_storage_sync:
        destination: "{{ bucket_name }}"
        source: "{{ project_root }}/{{ build_dir }}/"
        delete: true
        recursion: true
